name: Update skjemabygger on new tag
on:
  push:
jobs:
  create-PR:
    name: "Triggers pull request in skjemautfyller"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout skjemautfyller
        uses: actions/checkout@v2
        with:
          repository: navikt/skjemautfylling-formio
          token: ${{ secrets.SKJEMAPUBLISERING_TOKEN }}
      - name: Test done
        run: echo "DONE"
