name: Update skjemabygger on new tag
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  create-PR:
    name: "Triggers pull request in skjemautfyller"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout skjemautfyller
        uses: actions/checkout@v2
        with:
          repository: navikt/skjemautfylling-formio
          token: ${{ secrets.SKJEMAPUBLISERING_TOKEN }}
          ref: skjemapublisering
          fetch-depth: 0
      - name: Set skjemapublisering tag
        run: echo ::set-env name=SKJEMAPUBLISERING_TAG::${GITHUB_REF#refs/*/}
      - name: Set new skjemapublisering url and tag
        run: echo ::set-env name=NEW_SKJEMAPUBLISERING_URL::git+https://github.com/navikt/skjemapublisering-test.git#$(echo ${SKJEMAPUBLISERING_TAG})
      - name: Update skjemapublisering version
        run: echo "`jq --arg skjemapubliseringsUrl "$NEW_SKJEMAPUBLISERING_URL" '.dependencies.skjemapublisering=$skjemapubliseringsUrl' package.json`" > package.json
      - name: Check package.json
        run: cat package.json
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Bump skjemapublisering dependency" -a
      - name: Push changes
        uses: ad-m/github-push-action@skjemapublisering
        with:
          github_token: ${{ secrets.SKJEMAPUBLISERING_TOKEN }}
