name: Update skjemautfyller on new tag
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - exact-commit-sha
      - master
jobs:
  commit-and-push-to-skjemautfyller:
    name: "Triggers a bump of the skjemapublisering dependency in skjemautfyller"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout skjemautfyller
        uses: actions/checkout@v2
        with:
          repository: navikt/skjemautfylling-formio
          token: ${{ secrets.SKJEMAPUBLISERING_TOKEN }}
          ref: flesktest
          fetch-depth: 0
      - name: Set new skjemapublisering url using the current commit sha
        run: echo ::set-env name=NEW_SKJEMAPUBLISERING_URL::navikt/skjemapublisering-test.git#$GITHUB_SHA
      - name: Debug stuffs
        run: 'echo URL $NEW_SKJEMAPUBLISERING_URL SHA $GITHUB_SHA'
      - name: Update skjemapublisering version
        run: echo "`jq --arg skjemapubliseringsUrl "$NEW_SKJEMAPUBLISERING_URL" '.dependencies.skjemapublisering=$skjemapubliseringsUrl' package.json`" > package.json
      - name: Check package.json
        run: npm install
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package*.json
          git commit -m "Bump skjemapublisering dependency"
      - name: Push changes
        run: git push
