name: Update skjemabygger on new tag
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  create-PR:
    name: "Triggers pull request in skjemautfyller"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout skjemautfyller
        uses: actions/checkout@v2
        with:
          repository: navikt/skjemautfylling-formio
          token: ${{ secrets.SKJEMAPUBLISERING_TOKEN }}
          ref: skjemapublisering
      - name: Get tag
        run: echo ::set-env name=SKJEMAPUBLISERING_TAG::${GITHUB_REF#refs/*/}
      - name: Check files
        run: ls
      - name: Update skjemapublisering version
        run: echo "`jq --arg skjemapubliseringsUrl "$NEW_SKJEMAPUBLISERING_URL" '.dependencies.skjemapublisering=$skjemapubliseringsUrl' package.json`" > package.json
        env:
          NEW_SKJEMAPUBLISERING_URL: git+https://github.com/navikt/skjemapublisering-test.git#${{SKJEMAPUBLISERING_TAG}}
      - name: Check package.json
        run: cat package.json
