name: Update skjemautfyller on master push
on:
  push:
    branches:
      - exact-commit-sha
      - master
jobs:
  update-skjemautfyller-master:
    name: "Triggers a bump of the skjemapublisering dependency in skjemautfyller"
    runs-on: ubuntu-latest
    env:
      PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
      PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
      PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
      PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
    steps:
      - name: Checkout skjemautfyller
        uses: actions/checkout@v2
        with:
          repository: navikt/skjemautfylling-formio
          token: ${{ secrets.SKJEMAPUBLISERING_TOKEN }}
          ref: master
          fetch-depth: 0
      - name: Set new skjemapublisering url using the current commit sha
        run: echo ::set-env name=NEW_SKJEMAPUBLISERING_URL::navikt/skjemapublisering.git#$GITHUB_SHA
      - name: Update skjemapublisering version
        run: echo "`jq --arg skjemapubliseringsUrl "$NEW_SKJEMAPUBLISERING_URL" '.dependencies.skjemapublisering=$skjemapubliseringsUrl' package.json`" > package.json
      - name: Check package.json and generate package-lock.json
        run: npm install
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package*.json
          git commit -m "Bump skjemapublisering dependency to $NEW_SKJEMAPUBLISERING_URL"
      - name: Push changes
        run: git push
      - name: Send message when job fails
        if: ${{ failure() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.js build-aborted
